PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS moods (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mood TEXT NOT NULL CHECK (mood IN ('happy','neutral','sad')),
  alias TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_alias TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL,
  body TEXT NOT NULL,
  anon INTEGER NOT NULL DEFAULT 1,   -- 1=true, 0=false
  alias TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS counselors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  specialty TEXT,
  languages TEXT,
  bio TEXT,
  cal_link TEXT,
  visible INTEGER DEFAULT 1
);
